"""Abstract interface for LLM providers."""
from abc import ABC, abstractmethod


class LLMInterface(ABC):
    """Abstract base class defining the contract for any LLM provider integration."""

    @abstractmethod
    def invoke(self, prompt: str, tools: list) -> str:
        """Invoke the LLM with a prompt and an optional list of tools.

        Args:
            prompt: The input prompt to send to the LLM.
            tools: A list of tools the LLM may use during invocation.

        Returns:
            The string response generated by the LLM.
        """
        raise NotImplementedError
